Feature/kyv 570 create invoice
City-of-Helsinki/verkkokauppa-kassa-ui pull request #112
Opened 2022-09-14 09:50 UTC by severikupari1

2022-09-23 07:05 UTC, martinldev requested changes

2022-09-23 07:05 UTC, martinldev commented on src/components/InvoiceDetails.tsx
> +            { ({ errors, touched, isSubmitting }) => (
I am not sure how this will be treated on re-render. I'd change this to a named function and call the function here. Function name could be "renderInvoiceForm(...)" etc.

2022-09-23 09:52 UTC, severikupari1 commented on src/components/InvoiceDetails.tsx
> +            validate={ (values) => {
I am not sure if we can change this, because these are taken from Formik npm library examples. I can try to change these and I will test if form works as wanted.

2022-09-26 09:54 UTC, martinldev commented
No need to fix the anonymous functions - performance will not be impacted from a few declared anonymous functions.

2022-09-26 09:55 UTC, martinldev approved these changes

2022-09-26 09:55 UTC, merged